schema_version: 1

context:
  version: "0.2.dev3"  # kept in sync with pyproject.toml by misc/push_to_conda.sh

package:
  name: knightswhosaydb
  version: ${{ version }}

source:
  path: ../
  filter:
    exclude:
      - output/**
      - .venv/**

build:
  noarch: python
  script: python -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python >=3.12
    - pip
    - hatchling
  run:
    - python >=3.12
    - themachinethatgoesping >=0.36.0,<0.37
    - rasterio >=1.5.0,<2


tests:
  - python:
      imports:
        - knightswhosaydb
      pip_check: false

about:
  summary: "Multibeam backscatter reading and processing"
  license: MIT
  license_file: LICENSE
