[workspace]
name = "knightswhosaydb"
channels = ["conda-forge", "themachinethatgoesping"]
platforms = [
    "linux-64",
    "osx-arm64",
    "win-64",
]

[dependencies]
python = ">=3.12"
hatchling = ">=1.32.0,<2"
pip = ">=26.2.1,<27"
pytest = ">=9.1.1,<10"
nbmake = ">=1.5.5,<2"
themachinethatgoesping = ">=0.35.2.dev6,<0.36"

[feature.build.dependencies]
python-build = ">=1.6.0,<2"
twine = ">=7.0.0,<8"
anaconda-client = ">=1.14.1,<2"
rattler-build = ">=0.75.0,<0.76"

[feature.build.tasks]
test = "python -m pytest -v tests/"
build-pypi = "python -m build"
upload-pypi = { cmd = "twine upload dist/*", depends-on = ["build-pypi"] }
build-conda = "rattler-build build --recipe recipe/recipe.yaml --output output"
clean_notebooks = "python misc/clean_notebooks.py"

[environments]
default = { solve-group = "default" }
build = { features = ["build"], solve-group = "default" }

